export enum GigStatus {
  DRAFT = 'DRAFT',
  PUBLISHED = 'PUBLISHED',
  APPLICATIONS_CLOSED = 'APPLICATIONS_CLOSED',
  CLOSED = 'CLOSED', // Alias for APPLICATIONS_CLOSED for backward compatibility
  BOOKED = 'BOOKED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED'
}