-- =====================================================
-- ADDITIONAL SKILLS FOR COLLABORATION PROJECTS
-- =====================================================
-- Migration: 101_additional_skills.sql
-- Description: Add more comprehensive skills to predefined_skills table

-- Insert additional technical skills
INSERT INTO predefined_skills (name, category, description, sort_order) VALUES
-- Advanced Technical Skills
('Camera Operation', 'technical', 'Operating various camera systems and equipment', 60),
('Lens Selection', 'technical', 'Choosing appropriate lenses for different scenarios', 61),
('Exposure Control', 'technical', 'Mastering aperture, shutter speed, and ISO settings', 62),
('Focus Techniques', 'technical', 'Advanced focusing methods and techniques', 63),
('White Balance', 'technical', 'Color temperature and white balance adjustment', 64),
('Metering', 'technical', 'Light metering and exposure measurement', 65),
('Composition', 'technical', 'Visual composition and framing techniques', 66),
('Depth of Field', 'technical', 'Controlling depth of field and bokeh effects', 67),
('Camera Movement', 'technical', 'Panning, tilting, and camera stabilization', 68),
('Slow Motion', 'technical', 'High frame rate and slow motion techniques', 69),
('Time-lapse', 'technical', 'Creating time-lapse sequences', 70),
('Macro Photography', 'technical', 'Close-up and macro photography techniques', 71),
('Portrait Photography', 'technical', 'Professional portrait photography', 72),
('Landscape Photography', 'technical', 'Outdoor and landscape photography', 73),
('Street Photography', 'technical', 'Candid and street photography', 74),
('Event Photography', 'technical', 'Wedding and event photography', 75),
('Product Photography', 'technical', 'Commercial product photography', 76),
('Food Photography', 'technical', 'Culinary and food photography', 77),
('Architectural Photography', 'technical', 'Building and architectural photography', 78),
('Sports Photography', 'technical', 'Action and sports photography', 79),
('Wildlife Photography', 'technical', 'Animal and wildlife photography', 80),
('Astrophotography', 'technical', 'Night sky and astronomical photography', 81),
('Underwater Photography', 'technical', 'Aquatic and underwater photography', 82),
('Aerial Photography', 'technical', 'Drone and aerial photography', 83),
('360 Photography', 'technical', 'Panoramic and 360-degree photography', 84),
('HDR Photography', 'technical', 'High Dynamic Range photography', 85),
('Long Exposure', 'technical', 'Long exposure and light trail photography', 86),
('Flash Photography', 'technical', 'On-camera and off-camera flash techniques', 87),
('Natural Light', 'technical', 'Working with natural lighting conditions', 88),
('Studio Lighting', 'technical', 'Professional studio lighting setups', 89),
('Color Temperature', 'technical', 'Understanding and controlling color temperature', 90),
('Light Modifiers', 'technical', 'Using reflectors, diffusers, and modifiers', 91),
('Lighting Ratios', 'technical', 'Understanding lighting ratios and contrast', 92),
('Rembrandt Lighting', 'technical', 'Classic portrait lighting techniques', 93),
('Butterfly Lighting', 'technical', 'High-key portrait lighting', 94),
('Split Lighting', 'technical', 'Dramatic split lighting techniques', 95),
('Backlighting', 'technical', 'Creative backlighting techniques', 96),
('Silhouette Photography', 'technical', 'Creating dramatic silhouettes', 97),
('Golden Hour', 'technical', 'Photographing during golden hour', 98),
('Blue Hour', 'technical', 'Photographing during blue hour', 99),
('Night Photography', 'technical', 'Low-light and night photography', 100)
ON CONFLICT (name) DO NOTHING;

-- Insert additional creative skills
INSERT INTO predefined_skills (name, category, description, sort_order) VALUES
-- Advanced Creative Skills
('Posing', 'creative', 'Directing and posing subjects for photography', 101),
('Expression Direction', 'creative', 'Guiding facial expressions and emotions', 102),
('Body Language', 'creative', 'Understanding and directing body language', 103),
('Character Development', 'creative', 'Creating and developing characters', 104),
('Scene Blocking', 'creative', 'Blocking and staging scenes', 105),
('Visual Storytelling', 'creative', 'Telling stories through visual elements', 106),
('Mood Creation', 'creative', 'Creating specific moods and atmospheres', 107),
('Color Psychology', 'creative', 'Using color to evoke emotions', 108),
('Texture Design', 'creative', 'Creating and working with textures', 109),
('Pattern Recognition', 'creative', 'Identifying and using visual patterns', 110),
('Symmetry', 'creative', 'Using symmetry in composition', 111),
('Asymmetry', 'creative', 'Creating balanced asymmetrical compositions', 112),
('Rule of Thirds', 'creative', 'Applying rule of thirds in composition', 113),
('Leading Lines', 'creative', 'Using lines to guide viewer attention', 114),
('Negative Space', 'creative', 'Using negative space effectively', 115),
('Framing', 'creative', 'Using natural and artificial frames', 116),
('Perspective', 'creative', 'Working with different perspectives', 117),
('Scale', 'creative', 'Using scale to create impact', 118),
('Contrast', 'creative', 'Creating visual contrast', 119),
('Harmony', 'creative', 'Creating visual harmony', 120),
('Rhythm', 'creative', 'Creating visual rhythm and flow', 121),
('Emphasis', 'creative', 'Creating focal points and emphasis', 122),
('Unity', 'creative', 'Creating visual unity', 123),
('Variety', 'creative', 'Adding visual variety', 124),
('Balance', 'creative', 'Creating visual balance', 125),
('Proportion', 'creative', 'Understanding and using proportion', 126),
('Movement', 'creative', 'Creating sense of movement', 127),
('Stillness', 'creative', 'Creating sense of stillness', 128),
('Tension', 'creative', 'Creating visual tension', 129),
('Release', 'creative', 'Creating visual release', 130),
('Drama', 'creative', 'Creating dramatic effects', 131),
('Subtlety', 'creative', 'Creating subtle effects', 132),
('Boldness', 'creative', 'Creating bold visual statements', 133),
('Minimalism', 'creative', 'Creating minimalist compositions', 134),
('Maximalism', 'creative', 'Creating rich, complex compositions', 135),
('Abstraction', 'creative', 'Creating abstract imagery', 136),
('Realism', 'creative', 'Creating realistic imagery', 137),
('Surrealism', 'creative', 'Creating surreal imagery', 138),
('Conceptual Art', 'creative', 'Creating conceptual imagery', 139),
('Fine Art', 'creative', 'Creating fine art photography', 140),
('Commercial Art', 'creative', 'Creating commercial imagery', 141),
('Editorial', 'creative', 'Creating editorial imagery', 142),
('Documentary', 'creative', 'Creating documentary imagery', 143),
('Photojournalism', 'creative', 'Creating photojournalistic imagery', 144),
('Fashion', 'creative', 'Creating fashion imagery', 145),
('Beauty', 'creative', 'Creating beauty imagery', 146),
('Lifestyle', 'creative', 'Creating lifestyle imagery', 147),
('Travel', 'creative', 'Creating travel imagery', 148),
('Adventure', 'creative', 'Creating adventure imagery', 149),
('Nature', 'creative', 'Creating nature imagery', 150)
ON CONFLICT (name) DO NOTHING;

-- Insert additional software skills
INSERT INTO predefined_skills (name, category, description, sort_order) VALUES
-- Advanced Software Skills
('Capture One', 'software', 'Professional photo editing with Capture One', 151),
('Luminar', 'software', 'AI-powered photo editing with Luminar', 152),
('Skylum', 'software', 'Creative photo editing with Skylum software', 153),
('ON1 Photo RAW', 'software', 'All-in-one photo editing with ON1', 154),
('DxO PhotoLab', 'software', 'Professional photo editing with DxO', 155),
('Topaz Labs', 'software', 'AI-powered photo enhancement tools', 156),
('Nik Collection', 'software', 'Professional photo filters and effects', 157),
('Silver Efex Pro', 'software', 'Black and white photo processing', 158),
('Color Efex Pro', 'software', 'Color enhancement and effects', 159),
('HDR Efex Pro', 'software', 'HDR photo processing', 160),
('Sharpener Pro', 'software', 'Professional image sharpening', 161),
('Dfine', 'software', 'Noise reduction software', 162),
('Viveza', 'software', 'Selective color and light adjustment', 163),
('Analog Efex Pro', 'software', 'Vintage film effects', 164),
('Blender', 'software', '3D modeling and animation', 165),
('Cinema 4D', 'software', '3D modeling and animation', 166),
('Maya', 'software', '3D modeling and animation', 167),
('3ds Max', 'software', '3D modeling and animation', 168),
('ZBrush', 'software', 'Digital sculpting', 169),
('Substance Painter', 'software', '3D texture painting', 170),
('Substance Designer', 'software', 'Procedural texture creation', 171),
('Houdini', 'software', 'Procedural 3D animation', 172),
('Nuke', 'software', 'Professional compositing', 173),
('Fusion', 'software', 'Node-based compositing', 174),
('Resolve', 'software', 'Professional color grading and editing', 175),
('Baselight', 'software', 'Professional color grading', 176),
('Scratch', 'software', 'Professional color grading', 177),
('Flame', 'software', 'Professional finishing and effects', 178),
('Smoke', 'software', 'Professional editing and finishing', 179),
('Avid Symphony', 'software', 'Professional editing and finishing', 180),
('Media Composer', 'software', 'Professional video editing', 181),
('Premiere Rush', 'software', 'Mobile video editing', 182),
('DaVinci Resolve', 'software', 'Professional color grading and editing', 183),
('HitFilm', 'software', 'Video editing and effects', 184),
('Vegas Pro', 'software', 'Professional video editing', 185),
('Camtasia', 'software', 'Screen recording and editing', 186),
('OBS Studio', 'software', 'Live streaming and recording', 187),
('Streamlabs', 'software', 'Live streaming software', 188),
('Wirecast', 'software', 'Professional live streaming', 189),
('vMix', 'software', 'Live video production', 190),
('ProPresenter', 'software', 'Live presentation software', 191),
('Keynote', 'software', 'Presentation software', 192),
('PowerPoint', 'software', 'Presentation software', 193),
('Canva', 'software', 'Graphic design platform', 194),
('Figma', 'software', 'Collaborative design tool', 195),
('Sketch', 'software', 'Digital design tool', 196),
('InVision', 'software', 'Design prototyping', 197),
('Principle', 'software', 'Animation and prototyping', 198),
('Framer', 'software', 'Interactive design tool', 199),
('Webflow', 'software', 'Web design and development', 200)
ON CONFLICT (name) DO NOTHING;

-- Insert additional interpersonal skills
INSERT INTO predefined_skills (name, category, description, sort_order) VALUES
-- Advanced Interpersonal Skills
('Active Listening', 'interpersonal', 'Fully concentrating on and understanding others', 201),
('Empathy', 'interpersonal', 'Understanding and sharing others feelings', 202),
('Conflict Resolution', 'interpersonal', 'Resolving disagreements and conflicts', 203),
('Negotiation', 'interpersonal', 'Reaching mutually beneficial agreements', 204),
('Public Speaking', 'interpersonal', 'Speaking effectively to groups', 205),
('Presentation Skills', 'interpersonal', 'Delivering engaging presentations', 206),
('Networking', 'interpersonal', 'Building professional relationships', 207),
('Mentoring', 'interpersonal', 'Guiding and developing others', 208),
('Coaching', 'interpersonal', 'Helping others improve performance', 209),
('Training', 'interpersonal', 'Teaching and developing skills', 210),
('Feedback Delivery', 'interpersonal', 'Providing constructive feedback', 211),
('Feedback Reception', 'interpersonal', 'Receiving and acting on feedback', 212),
('Cultural Sensitivity', 'interpersonal', 'Working effectively across cultures', 213),
('Diversity Awareness', 'interpersonal', 'Understanding and valuing differences', 214),
('Emotional Intelligence', 'interpersonal', 'Understanding and managing emotions', 215),
('Adaptability', 'interpersonal', 'Adjusting to changing situations', 216),
('Flexibility', 'interpersonal', 'Being open to change and new ideas', 217),
('Patience', 'interpersonal', 'Maintaining composure in difficult situations', 218),
('Diplomacy', 'interpersonal', 'Handling sensitive situations tactfully', 219),
('Tact', 'interpersonal', 'Being considerate and sensitive', 220),
('Professionalism', 'interpersonal', 'Maintaining professional standards', 221),
('Work Ethic', 'interpersonal', 'Demonstrating strong work principles', 222),
('Reliability', 'interpersonal', 'Being dependable and consistent', 223),
('Integrity', 'interpersonal', 'Maintaining ethical standards', 224),
('Accountability', 'interpersonal', 'Taking responsibility for actions', 225),
('Transparency', 'interpersonal', 'Being open and honest', 226),
('Trust Building', 'interpersonal', 'Creating trust in relationships', 227),
('Credibility', 'interpersonal', 'Being believable and trustworthy', 228),
('Influence', 'interpersonal', 'Persuading and motivating others', 229),
('Motivation', 'interpersonal', 'Inspiring and encouraging others', 230),
('Inspiration', 'interpersonal', 'Motivating others to achieve goals', 231),
('Encouragement', 'interpersonal', 'Supporting and uplifting others', 232),
('Support', 'interpersonal', 'Providing assistance and backing', 233),
('Collaboration', 'interpersonal', 'Working effectively with others', 234),
('Cooperation', 'interpersonal', 'Working together toward common goals', 235),
('Teamwork', 'interpersonal', 'Contributing to team success', 236),
('Synergy', 'interpersonal', 'Creating combined effects greater than sum of parts', 237),
('Consensus Building', 'interpersonal', 'Reaching agreement among group members', 238),
('Facilitation', 'interpersonal', 'Guiding group processes', 239),
('Mediation', 'interpersonal', 'Helping resolve disputes', 240),
('Arbitration', 'interpersonal', 'Making binding decisions in disputes', 241),
('Crisis Management', 'interpersonal', 'Handling emergency situations', 242),
('Stress Management', 'interpersonal', 'Managing pressure and stress', 243),
('Resilience', 'interpersonal', 'Bouncing back from setbacks', 244),
('Perseverance', 'interpersonal', 'Continuing despite difficulties', 245),
('Determination', 'interpersonal', 'Firmness of purpose', 246),
('Persistence', 'interpersonal', 'Continuing despite obstacles', 247),
('Optimism', 'interpersonal', 'Maintaining positive outlook', 248),
('Positivity', 'interpersonal', 'Maintaining positive attitude', 249),
('Enthusiasm', 'interpersonal', 'Showing excitement and energy', 250)
ON CONFLICT (name) DO NOTHING;

-- Insert additional specialized skills
INSERT INTO predefined_skills (name, category, description, sort_order) VALUES
-- Advanced Specialized Skills
('Crisis Communication', 'specialized', 'Managing communication during crises', 251),
('Media Relations', 'specialized', 'Working with media and press', 252),
('Public Relations', 'specialized', 'Managing public image and reputation', 253),
('Brand Strategy', 'specialized', 'Developing brand positioning and strategy', 254),
('Market Research', 'specialized', 'Conducting market analysis and research', 255),
('Competitive Analysis', 'specialized', 'Analyzing competitors and market position', 256),
('Customer Segmentation', 'specialized', 'Identifying and targeting customer groups', 257),
('Persona Development', 'specialized', 'Creating customer personas', 258),
('Journey Mapping', 'specialized', 'Mapping customer experience journeys', 259),
('User Experience Design', 'specialized', 'Designing user-centered experiences', 260),
('User Interface Design', 'specialized', 'Designing user interfaces', 261),
('Information Architecture', 'specialized', 'Organizing and structuring information', 262),
('Usability Testing', 'specialized', 'Testing product usability', 263),
('A/B Testing', 'specialized', 'Conducting split tests', 264),
('Conversion Optimization', 'specialized', 'Improving conversion rates', 265),
('Funnel Analysis', 'specialized', 'Analyzing conversion funnels', 266),
('Cohort Analysis', 'specialized', 'Analyzing user behavior over time', 267),
('Retention Analysis', 'specialized', 'Analyzing user retention', 268),
('Churn Analysis', 'specialized', 'Analyzing customer churn', 269),
('Lifetime Value Analysis', 'specialized', 'Calculating customer lifetime value', 270),
('ROI Analysis', 'specialized', 'Analyzing return on investment', 271),
('KPI Development', 'specialized', 'Developing key performance indicators', 272),
('Dashboard Creation', 'specialized', 'Creating data dashboards', 273),
('Report Writing', 'specialized', 'Writing analytical reports', 274),
('Data Visualization', 'specialized', 'Creating visual representations of data', 275),
('Statistical Analysis', 'specialized', 'Conducting statistical analysis', 276),
('Predictive Modeling', 'specialized', 'Creating predictive models', 277),
('Machine Learning', 'specialized', 'Implementing ML algorithms', 278),
('Artificial Intelligence', 'specialized', 'Working with AI systems', 279),
('Automation', 'specialized', 'Automating processes and workflows', 280),
('Workflow Design', 'specialized', 'Designing efficient workflows', 281),
('Process Improvement', 'specialized', 'Improving business processes', 282),
('Quality Assurance', 'specialized', 'Ensuring quality standards', 283),
('Testing', 'specialized', 'Conducting various types of testing', 284),
('Debugging', 'specialized', 'Identifying and fixing issues', 285),
('Troubleshooting', 'specialized', 'Diagnosing and solving problems', 286),
('System Administration', 'specialized', 'Managing computer systems', 287),
('Network Administration', 'specialized', 'Managing network infrastructure', 288),
('Security Management', 'specialized', 'Managing information security', 289),
('Compliance', 'specialized', 'Ensuring regulatory compliance', 290),
('Risk Management', 'specialized', 'Identifying and managing risks', 291),
('Change Management', 'specialized', 'Managing organizational change', 292),
('Project Planning', 'specialized', 'Planning and organizing projects', 293),
('Resource Management', 'specialized', 'Managing project resources', 294),
('Vendor Management', 'specialized', 'Managing vendor relationships', 295),
('Contract Management', 'specialized', 'Managing contracts and agreements', 296),
('Legal Compliance', 'specialized', 'Ensuring legal compliance', 297),
('Intellectual Property', 'specialized', 'Managing IP rights and protection', 298),
('Trademark Law', 'specialized', 'Understanding trademark regulations', 299),
('Copyright Law', 'specialized', 'Understanding copyright regulations', 300)
ON CONFLICT (name) DO NOTHING;

-- Update the migration log
INSERT INTO system_alerts (type, level, message, metadata)
VALUES (
    'migration_completed',
    'info',
    'Additional skills migration completed successfully',
    '{"migration": "101_additional_skills.sql", "skills_added": 242, "total_skills": 301}'
) ON CONFLICT DO NOTHING;
