-- Add predefined nationalities table
-- This provides a dropdown list of nationalities sorted alphabetically

CREATE TABLE IF NOT EXISTS predefined_nationalities (
  id SERIAL PRIMARY KEY,
  nationality_name VARCHAR(100) NOT NULL UNIQUE,
  country_code VARCHAR(3),
  is_active BOOLEAN DEFAULT true,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Insert nationalities (sorted alphabetically)
INSERT INTO predefined_nationalities (nationality_name, country_code, sort_order) VALUES
('Afghan', 'AFG', 1),
('Albanian', 'ALB', 2),
('Algerian', 'DZA', 3),
('American', 'USA', 4),
('Andorran', 'AND', 5),
('Angolan', 'AGO', 6),
('Argentine', 'ARG', 7),
('Armenian', 'ARM', 8),
('Australian', 'AUS', 9),
('Austrian', 'AUT', 10),
('Azerbaijani', 'AZE', 11),
('Bahamian', 'BHS', 12),
('Bahraini', 'BHR', 13),
('Bangladeshi', 'BGD', 14),
('Barbadian', 'BRB', 15),
('Belarusian', 'BLR', 16),
('Belgian', 'BEL', 17),
('Belizean', 'BLZ', 18),
('Beninese', 'BEN', 19),
('Bhutanese', 'BTN', 20),
('Bolivian', 'BOL', 21),
('Bosnian', 'BIH', 22),
('Botswanan', 'BWA', 23),
('Brazilian', 'BRA', 24),
('British', 'GBR', 25),
('Bruneian', 'BRN', 26),
('Bulgarian', 'BGR', 27),
('Burkinabe', 'BFA', 28),
('Burmese', 'MMR', 29),
('Burundian', 'BDI', 30),
('Cambodian', 'KHM', 31),
('Cameroonian', 'CMR', 32),
('Canadian', 'CAN', 33),
('Cape Verdean', 'CPV', 34),
('Central African', 'CAF', 35),
('Chadian', 'TCD', 36),
('Chilean', 'CHL', 37),
('Chinese', 'CHN', 38),
('Colombian', 'COL', 39),
('Comoran', 'COM', 40),
('Congolese', 'COG', 41),
('Costa Rican', 'CRI', 42),
('Croatian', 'HRV', 43),
('Cuban', 'CUB', 44),
('Cypriot', 'CYP', 45),
('Czech', 'CZE', 46),
('Danish', 'DNK', 47),
('Djiboutian', 'DJI', 48),
('Dominican', 'DOM', 49),
('Dutch', 'NLD', 50),
('Ecuadorian', 'ECU', 51),
('Egyptian', 'EGY', 52),
('Emirati', 'ARE', 53),
('English', 'ENG', 54),
('Eritrean', 'ERI', 55),
('Estonian', 'EST', 56),
('Ethiopian', 'ETH', 57),
('Fijian', 'FJI', 58),
('Filipino', 'PHL', 59),
('Finnish', 'FIN', 60),
('French', 'FRA', 61),
('Gabonese', 'GAB', 62),
('Gambian', 'GMB', 63),
('Georgian', 'GEO', 64),
('German', 'DEU', 65),
('Ghanaian', 'GHA', 66),
('Greek', 'GRC', 67),
('Grenadian', 'GRD', 68),
('Guatemalan', 'GTM', 69),
('Guinean', 'GIN', 70),
('Guyanese', 'GUY', 71),
('Haitian', 'HTI', 72),
('Honduran', 'HND', 73),
('Hungarian', 'HUN', 74),
('Icelandic', 'ISL', 75),
('Indian', 'IND', 76),
('Indonesian', 'IDN', 77),
('Iranian', 'IRN', 78),
('Iraqi', 'IRQ', 79),
('Irish', 'IRL', 80),
('Israeli', 'ISR', 81),
('Italian', 'ITA', 82),
('Ivorian', 'CIV', 83),
('Jamaican', 'JAM', 84),
('Japanese', 'JPN', 85),
('Jordanian', 'JOR', 86),
('Kazakh', 'KAZ', 87),
('Kenyan', 'KEN', 88),
('Korean', 'KOR', 89),
('Kuwaiti', 'KWT', 90),
('Kyrgyz', 'KGZ', 91),
('Laotian', 'LAO', 92),
('Latvian', 'LVA', 93),
('Lebanese', 'LBN', 94),
('Liberian', 'LBR', 95),
('Libyan', 'LBY', 96),
('Lithuanian', 'LTU', 97),
('Luxembourgish', 'LUX', 98),
('Macedonian', 'MKD', 99),
('Malagasy', 'MDG', 100),
('Malawian', 'MWI', 101),
('Malaysian', 'MYS', 102),
('Maldivian', 'MDV', 103),
('Malian', 'MLI', 104),
('Maltese', 'MLT', 105),
('Mauritanian', 'MRT', 106),
('Mauritian', 'MUS', 107),
('Mexican', 'MEX', 108),
('Moldovan', 'MDA', 109),
('Monacan', 'MCO', 110),
('Mongolian', 'MNG', 111),
('Montenegrin', 'MNE', 112),
('Moroccan', 'MAR', 113),
('Mozambican', 'MOZ', 114),
('Namibian', 'NAM', 115),
('Nepalese', 'NPL', 116),
('New Zealander', 'NZL', 117),
('Nicaraguan', 'NIC', 118),
('Nigerian', 'NGA', 119),
('Nigerien', 'NER', 120),
('Norwegian', 'NOR', 121),
('Omani', 'OMN', 122),
('Pakistani', 'PAK', 123),
('Panamanian', 'PAN', 124),
('Paraguayan', 'PRY', 125),
('Peruvian', 'PER', 126),
('Polish', 'POL', 127),
('Portuguese', 'PRT', 128),
('Qatari', 'QAT', 129),
('Romanian', 'ROU', 130),
('Russian', 'RUS', 131),
('Rwandan', 'RWA', 132),
('Saudi', 'SAU', 133),
('Scottish', 'SCT', 134),
('Senegalese', 'SEN', 135),
('Serbian', 'SRB', 136),
('Singaporean', 'SGP', 137),
('Slovak', 'SVK', 138),
('Slovenian', 'SVN', 139),
('Somali', 'SOM', 140),
('South African', 'ZAF', 141),
('Spanish', 'ESP', 142),
('Sri Lankan', 'LKA', 143),
('Sudanese', 'SDN', 144),
('Surinamese', 'SUR', 145),
('Swedish', 'SWE', 146),
('Swiss', 'CHE', 147),
('Syrian', 'SYR', 148),
('Taiwanese', 'TWN', 149),
('Tajik', 'TJK', 150),
('Tanzanian', 'TZA', 151),
('Thai', 'THA', 152),
('Togolese', 'TGO', 153),
('Trinidadian', 'TTO', 154),
('Tunisian', 'TUN', 155),
('Turkish', 'TUR', 156),
('Turkmen', 'TKM', 157),
('Ugandan', 'UGA', 158),
('Ukrainian', 'UKR', 159),
('Uruguayan', 'URY', 160),
('Uzbek', 'UZB', 161),
('Venezuelan', 'VEN', 162),
('Vietnamese', 'VNM', 163),
('Welsh', 'WLS', 164),
('Yemeni', 'YEM', 165),
('Zambian', 'ZMB', 166),
('Zimbabwean', 'ZWE', 167)
ON CONFLICT (nationality_name) DO NOTHING;

-- Create index
CREATE INDEX IF NOT EXISTS idx_predefined_nationalities_active ON predefined_nationalities(is_active, sort_order);

-- Enable RLS
ALTER TABLE predefined_nationalities ENABLE ROW LEVEL SECURITY;

-- Create RLS policy (public read access)
CREATE POLICY "Anyone can view predefined nationalities" ON predefined_nationalities
  FOR SELECT USING (true);

-- Create update timestamp trigger
CREATE TRIGGER update_predefined_nationalities_updated_at
    BEFORE UPDATE ON predefined_nationalities
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Add comment
COMMENT ON TABLE predefined_nationalities IS 'Predefined nationalities for user profiles (sorted alphabetically)';
COMMENT ON COLUMN predefined_nationalities.nationality_name IS 'Name of the nationality (e.g., "American", "British", "French")';
COMMENT ON COLUMN predefined_nationalities.country_code IS 'ISO 3166-1 alpha-3 country code';
